[package]
name          = "rustls-connector"
version       = "0.8.1" # remember to update html_root_url
authors       = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition       = "2018"
description   = "Connector similar to openssl or native-tls for rustls"
repository    = "https://github.com/Keruspe/rustls-connector"
documentation = "https://docs.rs/rustls-connector"
keywords      = ["tls", "rustls"]
categories    = ["network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "rustls_connector"

[features]
default                 = []
dangerous_configuration = [ "rustls/dangerous_configuration" ]
quic                    = [ "rustls/quic" ]

[dependencies]
rustls = { git = "https://github.com/deltachat/rustls" }
webpki = { git = "https://github.com/deltachat/webpki" }
webpki-roots = { git = "https://github.com/deltachat/webpki-roots" }
#rustls       = "^0.16"
#webpki       = "^0.21"
#webpki-roots = "^0.18"

[badges]
travis-ci = { repository = "Keruspe/rustls-connector" }
appveyor  = { repository = "Keruspe/rustls-connector" }
